// ALL user-facing strings, in every supported language. Care language only (§6):
// never 연구/실험/피험자-style vocabulary, never score/risk language. English is
// the DEFAULT and canonical shape; `npm run lint:copy` enforces the banned-word
// list on this file. Missing keys in a non-English locale fall back to English
// (see deepMerge below), so a partial translation is always safe.
//
// Coverage: en + ko are complete. es + zh cover the member-facing flow and the
// common staff chrome; the long-tail staff admin (people, study export) falls
// back to English pending a native-speaker pass — swap those in when reviewed.

export type Locale = "en" | "ko" | "es" | "zh";
export const LOCALES: { code: Locale; label: string }[] = [
  { code: "en", label: "English" },
  { code: "ko", label: "한국어" },
  { code: "es", label: "Español" },
  { code: "zh", label: "中文" },
];
export const DEFAULT_LOCALE: Locale = "en";

// ---- English (canonical) ---------------------------------------------------
const en = {
  appName: "Today's Record",

  checkin: {
    greeting: (name: string) => `Hello, ${name}!`,
    mood: "How are you feeling today?",
    energy: "How's your energy today?",
    pain: "Any aches or pain?",
    meds: "Did you take your medicine?",
    yes: "Yes",
    no: "No",
    done: "All done for today. Thank you!",
    alreadyDone: "You've already finished today. See you tomorrow!",
    companionGrew: "Your friend grew a little!",
    voiceAsk: "How was your day? Would you like to tell us?",
    voiceStart: "Start speaking",
    voiceStop: "I'm done",
    voiceSkip: "Skip",
    voiceNote: "Your voice is not saved.",
    offlineSaved: "Saved. It will send automatically when you're back online.",
    next: "Next",
  },

  faces: {
    mood: ["Very hard", "Hard", "Okay", "Good", "Very good"],
    energy: ["No energy", "A little low", "Okay", "Energetic", "Very energetic"],
    pain: ["A lot of pain", "In pain", "A little pain", "Fine", "Very good"],
  },

  trends: {
    title: "My changes",
    empty: "No records to show yet. Check in each day to see your changes.",
    bandLabel: { calm: "Steady", load: "Heavier", rest: "Please rest" },
    mood: "Mood",
    energy: "Energy",
    recentDays: "Last 30 days",
    reasons: {
      steady: "You're doing about the same as usual.",
      hr_high: "Your heart was a little busier than usual. Take it easy today.",
      recovery_low: "Your body had a little less rest than usual.",
      steps_low: "You moved a little less than usual. How about a gentle walk?",
    },
  },

  companion: {
    title: "My friend",
    stages: ["Egg", "Baby", "Child", "Youth", "Grown-up", "Shining friend"],
    message: (rate: number): string =>
      rate >= 0.5
        ? "You've been checking in well — your friend is growing!"
        : "Your friend grows each time you check in. Come see them today!",
  },

  pair: {
    title: "First time here!",
    explain: "Show this number to a staff member.",
    waiting: "Once they connect you, you're all set.",
    retry: "Get a new number",
  },

  staff: {
    login: "Staff sign-in",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    today: {
      title: "Today",
      notDone: "Not recorded today",
      allDone: "Everyone finished today 🎉",
      assist: "Record for them",
      markAway: "Away",
      markHospital: "Hospital",
      noteplaceholder: "Note…",
      saveNote: "Save note",
      doneList: "Recorded",
      pairDevice: "Link a phone",
      pairPrompt: "The 6-digit number on the member's phone",
      pairDone: "Linked.",
    },
    activities: {
      title: "Activities",
      create: "New activity",
      name: "Activity name (exercise, singing…)",
      intensity: "Physical intensity",
      intensityOpts: { none: "None", light: "Light", moderate: "Moderate" },
      start: "Start time",
      end: "End time",
      roster: "Members joining",
      save: "Save",
      summaryTitle: "Before & after at a glance",
      summaryNote:
        "For care reference only — it shows mood and body before and after together, not cause and effect.",
      moodBetter: (n: number, total: number) => `Mood improved for ${n} of ${total}`,
      noCaptures: "No before/after records yet.",
    },
    weekly: {
      title: "Weekly entry",
      pedometer: "Steps (Mon)",
      pedometerHint: "Enter the last 7 days left on the pedometer.",
      clinical: "Health check (Wed)",
      grip: "Grip (kg)",
      bp: "Blood pressure",
      weight: "Weight (kg)",
      save: "Save",
      saved: "Saved.",
    },
    people: {
      title: "Member management",
      add: "Enroll a member",
      name: "Name",
      photoUrl: "Photo URL (optional)",
      platform: "Phone type",
      platformOpts: { ios: "iPhone", android: "Android" },
      kiosk: "Device to use",
      kioskFixed: "Set once and it can't change. Always check on the same device.",
      kioskNone: "Not set yet",
      checkinMode: "Check-in mode",
      checkinModeOpts: { self: "On their own", self_nudge: "On their own (with reminders)", staff: "With staff help" },
      save: "Save",
      saved: "Saved.",
      enrolled: "Enrolled members",
      withdrawn: "Withdrawn",
      withdraw: "Withdraw",
      restore: "Re-enroll",
      confirmWithdraw: "Take this member off the list? Their records are kept.",
      consentTitle: "Care consent",
      consentSelf: "Can give consent themselves",
      consentRecords: "Consents to keeping today's records",
      consentPhoto: "Consents to showing the photo on the device",
      consentVoice: "Use voice-based records (optional)",
      consentVoiceNote: "The voice is not saved; only the information needed for the record is kept.",
      legalRepTitle: "Legal representative (when self-consent isn't possible)",
      legalRepName: "Representative's name",
      legalRepRel: "Relationship",
      legalRepPhone: "Contact",
      baselineTitle: "Health basics",
      adl: "Daily-living support level (ADL)",
      afFlag: "Has atrial fibrillation",
      afNote: "With atrial fibrillation, heart-rate variability isn't used. Heart rate is still shown.",
      betaBlocker: "Takes a beta-blocker",
      betaNote: "Important information that affects the heartbeat — please confirm.",
      rateControl: "Takes a rate-control medicine",
      anticholinergic: "Takes an anticholinergic",
      meds: "Medicines (one per line)",
      medsPlaceholder: "e.g. Aspirin 100mg",
      contactsTitle: "Emergency contacts",
      contactsNote: "For staff to call directly when needed. Nothing is ever contacted automatically.",
      contactName: "Name",
      contactRel: "Relationship",
      contactPhone: "Contact",
      contactShare: "Consents to sharing the contact",
      addContact: "Add contact",
      removeContact: "Remove",
    },
    study: {
      title: "Heart-rate records",
      note: "Only name-free records are gathered for export. Members never see this.",
      export: "Export (JSON)",
      subject: "No.",
      date: "Date",
      duration: "Length (s)",
      site: "Site",
      selfReport: "Self (0–10)",
      ref: "Reference",
      refInApp: "Together",
      refOffline: "Separate",
      video: "Video",
      viewVideo: "View video",
      hasVideo: "Yes",
      noVideo: "No",
      empty: "No records yet.",
      count: (n: number) => `${n} records`,
      disabled: "This feature isn't available right now.",
      tabRecords: "Records",
      tabVitals: "Vitals",
      tabProfiles: "Basics",
      name: "Name",
      birthYear: "Birth year",
      sexLabel: "Sex",
      heightCm: "Height (cm)",
      systolic: "Systolic",
      diastolic: "Diastolic",
      bodyTemp: "Temp (℃)",
      weightKg: "Weight (kg)",
      sleepHours: "Sleep (h)",
      activityRate: "Activity",
      save: "Save",
      saved: "Saved.",
      vitalsNeedRecording: "You need a recording first before adding vitals.",
      profilesEmpty: "No enrolled members.",
    },
    nav: { today: "Today", activities: "Activities", weekly: "Weekly" },
    navPeople: "Members",
    navStudy: "Export records",
  },

  common: {
    loading: "One moment…",
    error: "Something went wrong. Please try again.",
    back: "Back",
    confirm: "OK",
  },
};

export type Copy = typeof en;

type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends (...a: any[]) => any
    ? T[K]
    : T[K] extends readonly any[]
    ? T[K]
    : T[K] extends object
    ? DeepPartial<T[K]>
    : T[K];
};

// ---- 한국어 (complete) -----------------------------------------------------
const ko: DeepPartial<Copy> = {
  appName: "오늘의 기록",
  checkin: {
    greeting: (name: string) => `${name}님, 안녕하세요!`,
    mood: "오늘 기분이 어떠세요?",
    energy: "오늘 힘이 어떠세요?",
    pain: "어디 아프신 데 있나요?",
    meds: "약 드셨어요?",
    yes: "예",
    no: "아니요",
    done: "오늘 기록을 마쳤어요. 고맙습니다!",
    alreadyDone: "오늘은 이미 기록을 마치셨어요. 내일 또 만나요!",
    companionGrew: "친구가 조금 더 자랐어요!",
    voiceAsk: "오늘 어떻게 지내셨어요? 말씀해 주시겠어요?",
    voiceStart: "말하기 시작",
    voiceStop: "다 했어요",
    voiceSkip: "건너뛰기",
    voiceNote: "말씀하신 목소리는 저장되지 않아요.",
    offlineSaved: "기록을 저장했어요. 인터넷이 연결되면 자동으로 보내드려요.",
    next: "다음",
  },
  faces: {
    mood: ["아주 힘들어요", "힘들어요", "보통이에요", "좋아요", "아주 좋아요"],
    energy: ["기운이 없어요", "조금 없어요", "보통이에요", "기운나요", "아주 기운나요"],
    pain: ["많이 아파요", "아파요", "조금 아파요", "괜찮아요", "아주 좋아요"],
  },
  trends: {
    title: "나의 변화",
    empty: "아직 보여드릴 기록이 없어요. 매일 기록하면 변화를 볼 수 있어요.",
    bandLabel: { calm: "안정", load: "부담", rest: "소진" },
    mood: "기분",
    energy: "기운",
    recentDays: "지난 30일",
    reasons: {
      steady: "평소와 비슷하게 지내고 계세요.",
      hr_high: "평소보다 심장이 조금 바쁘게 뛰었어요. 오늘은 천천히 쉬어가요.",
      recovery_low: "평소보다 몸이 쉬는 시간이 조금 부족했어요.",
      steps_low: "평소보다 움직임이 조금 적었어요. 가볍게 걸어보는 건 어떨까요?",
    },
  },
  companion: {
    title: "나의 친구",
    stages: ["알", "아기", "어린이", "소년", "어른", "빛나는 친구"],
    message: (rate: number) =>
      rate >= 0.5
        ? "요즘 기록을 잘 해주셔서 친구가 쑥쑥 자라고 있어요!"
        : "기록할 때마다 친구가 자라나요. 오늘도 만나러 와주세요!",
  },
  pair: {
    title: "처음 오셨네요!",
    explain: "이 숫자를 센터 선생님께 보여주세요.",
    waiting: "선생님이 연결해 주시면 바로 시작돼요.",
    retry: "새 번호 받기",
  },
  staff: {
    login: "직원 로그인",
    email: "이메일",
    password: "비밀번호",
    signIn: "로그인",
    today: {
      title: "오늘",
      notDone: "오늘 안 한 사람",
      allDone: "오늘 모두 기록을 마쳤어요 🎉",
      assist: "대신 기록하기",
      markAway: "자리 비움",
      markHospital: "병원",
      noteplaceholder: "메모…",
      saveNote: "메모 저장",
      doneList: "기록한 분들",
      pairDevice: "휴대폰 연결",
      pairPrompt: "어르신 휴대폰에 보이는 6자리 숫자",
      pairDone: "연결됐어요.",
    },
    activities: {
      title: "활동",
      create: "새 활동 만들기",
      name: "활동 이름 (체조, 노래교실…)",
      intensity: "몸 쓰는 정도",
      intensityOpts: { none: "없음", light: "가벼움", moderate: "보통" },
      start: "시작 시간",
      end: "끝 시간",
      roster: "함께하는 분들",
      save: "저장",
      summaryTitle: "활동 전후 살펴보기",
      summaryNote:
        "돌봄 참고용이에요. 활동 전후의 기분과 몸 상태를 함께 본 것으로, 원인과 결과를 말해주는 것은 아니에요.",
      moodBetter: (n: number, total: number) => `기분이 좋아진 분 ${n}명 / ${total}명`,
      noCaptures: "아직 전후 기록이 없어요.",
    },
    weekly: {
      title: "주간 입력",
      pedometer: "걸음수 (월요일)",
      pedometerHint: "만보계에 남아있는 지난 7일을 입력하세요.",
      clinical: "건강 확인 (수요일)",
      grip: "악력(kg)",
      bp: "혈압",
      weight: "몸무게(kg)",
      save: "저장",
      saved: "저장했어요.",
    },
    people: {
      title: "어르신 관리",
      add: "새 어르신 등록",
      name: "성함",
      photoUrl: "사진 주소 (선택)",
      platform: "휴대폰 종류",
      platformOpts: { ios: "아이폰", android: "안드로이드" },
      kiosk: "사용할 확인 기기",
      kioskFixed: "한 번 정하면 바꿀 수 없어요. 늘 같은 기기로 확인해요.",
      kioskNone: "아직 정하지 않음",
      checkinMode: "기록 방식",
      checkinModeOpts: { self: "혼자서", self_nudge: "혼자서 (알림 도움)", staff: "직원 도움" },
      save: "저장",
      saved: "저장했어요.",
      enrolled: "등록된 어르신",
      withdrawn: "그만두신 분",
      withdraw: "그만두기",
      restore: "다시 등록",
      confirmWithdraw: "이 어르신을 목록에서 내릴까요? 기록은 그대로 보관돼요.",
      consentTitle: "돌봄 동의",
      consentSelf: "본인이 직접 동의하실 수 있어요",
      consentRecords: "오늘의 기록을 남기는 것에 동의해요",
      consentPhoto: "사진을 확인 기기에 보여주는 것에 동의해요",
      consentVoice: "목소리로 남기는 기록을 사용해요 (선택)",
      consentVoiceNote: "목소리는 저장하지 않고, 기록에 필요한 정보만 남겨요.",
      legalRepTitle: "대리인 (본인 동의가 어려울 때)",
      legalRepName: "대리인 성함",
      legalRepRel: "관계",
      legalRepPhone: "연락처",
      baselineTitle: "건강 기본 정보",
      adl: "일상생활 도움 정도 (ADL)",
      afFlag: "부정맥(심방세동)이 있어요",
      afNote: "부정맥이 있으면 심박 변동 값은 참고하지 않아요. 심박수는 그대로 확인해요.",
      betaBlocker: "베타차단제를 드세요",
      betaNote: "심박에 영향을 주는 중요한 정보예요. 꼭 확인해 주세요.",
      rateControl: "맥박 조절 약을 드세요",
      anticholinergic: "항콜린제를 드세요",
      meds: "드시는 약 (한 줄에 하나씩)",
      medsPlaceholder: "예: 아스피린 100mg",
      contactsTitle: "비상 연락처",
      contactsNote: "직원이 필요할 때 직접 연락하기 위한 것이에요. 어떤 경우에도 자동으로 연락하지 않아요.",
      contactName: "성함",
      contactRel: "관계",
      contactPhone: "연락처",
      contactShare: "연락처 공유에 동의",
      addContact: "연락처 추가",
      removeContact: "삭제",
    },
    study: {
      title: "심박 기록 자료",
      note: "이름을 뺀 기록만 모아 내보내요. 어르신께는 보이지 않아요.",
      export: "내보내기 (JSON)",
      subject: "번호",
      date: "날짜",
      duration: "길이(초)",
      site: "부위",
      selfReport: "본인 확인 (0–10)",
      ref: "기준 기기",
      refInApp: "함께 측정",
      refOffline: "따로 측정",
      video: "영상",
      viewVideo: "영상 보기",
      hasVideo: "있음",
      noVideo: "없음",
      empty: "아직 기록이 없어요.",
      count: (n: number) => `${n}개의 기록`,
      disabled: "이 기능은 지금 사용할 수 없어요.",
      tabRecords: "기록",
      tabVitals: "측정값",
      tabProfiles: "기본 정보",
      name: "이름",
      birthYear: "출생연도",
      sexLabel: "성별",
      heightCm: "키(cm)",
      systolic: "수축기",
      diastolic: "이완기",
      bodyTemp: "체온(℃)",
      weightKg: "몸무게(kg)",
      sleepHours: "수면(시간)",
      activityRate: "활동량",
      save: "저장",
      saved: "저장했어요.",
      vitalsNeedRecording: "먼저 기록이 있어야 측정값을 넣을 수 있어요.",
      profilesEmpty: "등록된 어르신이 없어요.",
    },
    nav: { today: "오늘", activities: "활동", weekly: "주간 입력" },
    navPeople: "어르신 관리",
    navStudy: "기록 내보내기",
  },
  common: {
    loading: "잠시만요…",
    error: "문제가 생겼어요. 다시 한번 해주세요.",
    back: "뒤로",
    confirm: "확인",
  },
};

// ---- Español (member-facing + common staff; rest falls back to English) ----
const es: DeepPartial<Copy> = {
  appName: "Registro de Hoy",
  checkin: {
    greeting: (name: string) => `¡Hola, ${name}!`,
    mood: "¿Cómo se siente hoy?",
    energy: "¿Cómo está su energía hoy?",
    pain: "¿Le duele algo?",
    meds: "¿Tomó su medicina?",
    yes: "Sí",
    no: "No",
    done: "Listo por hoy. ¡Gracias!",
    alreadyDone: "Ya terminó hoy. ¡Hasta mañana!",
    companionGrew: "¡Su amigo creció un poquito!",
    voiceAsk: "¿Cómo estuvo su día? ¿Quiere contarnos?",
    voiceStart: "Empezar a hablar",
    voiceStop: "Terminé",
    voiceSkip: "Omitir",
    voiceNote: "Su voz no se guarda.",
    offlineSaved: "Guardado. Se enviará automáticamente al reconectarse.",
    next: "Siguiente",
  },
  faces: {
    mood: ["Muy mal", "Mal", "Regular", "Bien", "Muy bien"],
    energy: ["Sin energía", "Algo baja", "Regular", "Con energía", "Con mucha energía"],
    pain: ["Mucho dolor", "Con dolor", "Poco dolor", "Bien", "Muy bien"],
  },
  trends: {
    title: "Mis cambios",
    empty: "Aún no hay registros. Regístrese cada día para ver sus cambios.",
    bandLabel: { calm: "Estable", load: "Más carga", rest: "Descanse" },
    mood: "Ánimo",
    energy: "Energía",
    recentDays: "Últimos 30 días",
    reasons: {
      steady: "Está más o menos como de costumbre.",
      hr_high: "Su corazón latió un poco más rápido de lo habitual. Tómelo con calma hoy.",
      recovery_low: "Su cuerpo descansó un poco menos de lo habitual.",
      steps_low: "Se movió un poco menos de lo habitual. ¿Qué tal un paseo suave?",
    },
  },
  companion: {
    title: "Mi amigo",
    stages: ["Huevo", "Bebé", "Niño", "Joven", "Adulto", "Amigo radiante"],
    message: (rate: number) =>
      rate >= 0.5
        ? "¡Se ha registrado muy bien y su amigo está creciendo!"
        : "Su amigo crece cada vez que se registra. ¡Venga hoy también!",
  },
  pair: {
    title: "¡Primera vez aquí!",
    explain: "Muestre este número al personal.",
    waiting: "En cuanto le conecten, todo listo.",
    retry: "Obtener un número nuevo",
  },
  staff: {
    login: "Acceso del personal",
    email: "Correo",
    password: "Contraseña",
    signIn: "Entrar",
    today: {
      title: "Hoy",
      notDone: "Sin registro hoy",
      allDone: "Todos terminaron hoy 🎉",
      assist: "Registrar por ellos",
      markAway: "Ausente",
      markHospital: "Hospital",
      noteplaceholder: "Nota…",
      saveNote: "Guardar nota",
      doneList: "Registrados",
      pairDevice: "Vincular teléfono",
      pairPrompt: "El número de 6 dígitos en el teléfono del miembro",
      pairDone: "Vinculado.",
    },
    activities: {
      title: "Actividades",
      create: "Nueva actividad",
      name: "Nombre (ejercicio, canto…)",
      intensity: "Intensidad física",
      intensityOpts: { none: "Ninguna", light: "Ligera", moderate: "Moderada" },
      start: "Hora de inicio",
      end: "Hora de fin",
      roster: "Miembros que participan",
      save: "Guardar",
      summaryTitle: "Antes y después de un vistazo",
      summaryNote:
        "Solo como referencia de cuidado — muestra ánimo y estado antes y después, no causa y efecto.",
      moodBetter: (n: number, total: number) => `Ánimo mejoró en ${n} de ${total}`,
      noCaptures: "Aún no hay registros de antes/después.",
    },
    weekly: {
      title: "Entrada semanal",
      pedometer: "Pasos (lun)",
      pedometerHint: "Ingrese los últimos 7 días del podómetro.",
      clinical: "Chequeo (mié)",
      grip: "Agarre (kg)",
      bp: "Presión arterial",
      weight: "Peso (kg)",
      save: "Guardar",
      saved: "Guardado.",
    },
    people: {
      title: "Gestión de miembros",
      add: "Inscribir un miembro",
      name: "Nombre",
      photoUrl: "URL de foto (opcional)",
      platform: "Tipo de teléfono",
      platformOpts: { ios: "iPhone", android: "Android" },
      kiosk: "Dispositivo a usar",
      kioskFixed: "Se define una vez y no se puede cambiar. Use siempre el mismo dispositivo.",
      kioskNone: "Sin definir",
      checkinMode: "Modo de registro",
      checkinModeOpts: { self: "Por su cuenta", self_nudge: "Por su cuenta (con recordatorios)", staff: "Con ayuda del personal" },
      save: "Guardar",
      saved: "Guardado.",
      enrolled: "Miembros inscritos",
      withdrawn: "Retirados",
      withdraw: "Retirar",
      restore: "Reinscribir",
      confirmWithdraw: "¿Quitar a este miembro de la lista? Sus registros se conservan.",
      consentTitle: "Consentimiento de cuidado",
      consentSelf: "Puede dar su consentimiento por sí mismo",
      consentRecords: "Consiente conservar los registros de hoy",
      consentPhoto: "Consiente mostrar la foto en el dispositivo",
      consentVoice: "Usar registros por voz (opcional)",
      consentVoiceNote: "La voz no se guarda; solo se conserva la información necesaria para el registro.",
      legalRepTitle: "Representante legal (cuando no puede consentir por sí mismo)",
      legalRepName: "Nombre del representante",
      legalRepRel: "Relación",
      legalRepPhone: "Contacto",
      baselineTitle: "Datos básicos de salud",
      adl: "Nivel de apoyo en la vida diaria (AVD)",
      afFlag: "Tiene fibrilación auricular",
      afNote: "Con fibrilación auricular no se usa la variabilidad del ritmo cardíaco. El ritmo cardíaco sí se muestra.",
      betaBlocker: "Toma un betabloqueante",
      betaNote: "Información importante que afecta el latido — por favor confirme.",
      rateControl: "Toma un medicamento para controlar el pulso",
      anticholinergic: "Toma un anticolinérgico",
      meds: "Medicamentos (uno por línea)",
      medsPlaceholder: "ej. Aspirina 100mg",
      contactsTitle: "Contactos de emergencia",
      contactsNote: "Para que el personal llame directamente cuando sea necesario. Nunca se contacta automáticamente.",
      contactName: "Nombre",
      contactRel: "Relación",
      contactPhone: "Contacto",
      contactShare: "Consiente compartir el contacto",
      addContact: "Agregar contacto",
      removeContact: "Eliminar",
    },
    study: {
      title: "Registros del ritmo cardíaco",
      note: "Solo se reúnen registros sin nombre para exportar. Los miembros nunca lo ven.",
      export: "Exportar (JSON)",
      subject: "N.º",
      date: "Fecha",
      duration: "Duración (s)",
      site: "Zona",
      selfReport: "Propio (0–10)",
      ref: "Referencia",
      refInApp: "Juntos",
      refOffline: "Aparte",
      video: "Video",
      viewVideo: "Ver video",
      hasVideo: "Sí",
      noVideo: "No",
      empty: "Aún no hay registros.",
      count: (n: number) => `${n} registros`,
      disabled: "Esta función no está disponible ahora.",
      tabRecords: "Registros",
      tabVitals: "Signos",
      tabProfiles: "Datos",
      name: "Nombre",
      birthYear: "Año de nacimiento",
      sexLabel: "Sexo",
      heightCm: "Estatura (cm)",
      systolic: "Sistólica",
      diastolic: "Diastólica",
      bodyTemp: "Temp (℃)",
      weightKg: "Peso (kg)",
      sleepHours: "Sueño (h)",
      activityRate: "Actividad",
      save: "Guardar",
      saved: "Guardado.",
      vitalsNeedRecording: "Necesita un registro antes de agregar signos.",
      profilesEmpty: "No hay miembros inscritos.",
    },
    nav: { today: "Hoy", activities: "Actividades", weekly: "Semanal" },
    navPeople: "Miembros",
    navStudy: "Exportar registros",
  },
  common: {
    loading: "Un momento…",
    error: "Algo salió mal. Inténtelo de nuevo.",
    back: "Atrás",
    confirm: "Aceptar",
  },
};

// ---- 中文 (member-facing + common staff; rest falls back to English) -------
const zh: DeepPartial<Copy> = {
  appName: "今日记录",
  checkin: {
    greeting: (name: string) => `${name}，您好！`,
    mood: "您今天感觉怎么样？",
    energy: "您今天精神怎么样？",
    pain: "有没有不舒服的地方？",
    meds: "您今天吃药了吗？",
    yes: "是",
    no: "否",
    done: "今天的记录完成了，谢谢！",
    alreadyDone: "今天已经完成了，明天见！",
    companionGrew: "您的朋友长大了一点！",
    voiceAsk: "今天过得怎么样？愿意说说吗？",
    voiceStart: "开始说话",
    voiceStop: "说完了",
    voiceSkip: "跳过",
    voiceNote: "您的声音不会被保存。",
    offlineSaved: "已保存。联网后会自动发送。",
    next: "下一步",
  },
  faces: {
    mood: ["很难受", "难受", "一般", "不错", "很好"],
    energy: ["没力气", "有点累", "一般", "有精神", "很有精神"],
    pain: ["很疼", "有点疼", "轻微疼", "还好", "很好"],
  },
  trends: {
    title: "我的变化",
    empty: "还没有记录。每天记录就能看到变化。",
    bandLabel: { calm: "平稳", load: "偏累", rest: "请休息" },
    mood: "心情",
    energy: "精神",
    recentDays: "近30天",
    reasons: {
      steady: "和平时差不多。",
      hr_high: "今天心跳比平时快了一些，今天就慢慢休息吧。",
      recovery_low: "今天身体休息的时间比平时少了一点。",
      steps_low: "今天活动比平时少了一些，要不要慢慢散散步？",
    },
  },
  companion: {
    title: "我的朋友",
    stages: ["蛋", "宝宝", "孩子", "少年", "成人", "闪耀的朋友"],
    message: (rate: number) =>
      rate >= 0.5
        ? "您坚持记录，朋友正在茁壮成长！"
        : "每次记录朋友都会长大。今天也来看看吧！",
  },
  pair: {
    title: "第一次来！",
    explain: "请把这个数字给工作人员看。",
    waiting: "工作人员连接后就可以开始了。",
    retry: "获取新号码",
  },
  staff: {
    login: "员工登录",
    email: "邮箱",
    password: "密码",
    signIn: "登录",
    today: {
      title: "今天",
      notDone: "今天未记录",
      allDone: "今天大家都完成了 🎉",
      assist: "代为记录",
      markAway: "请假",
      markHospital: "住院",
      noteplaceholder: "备注…",
      saveNote: "保存备注",
      doneList: "已记录",
      pairDevice: "关联手机",
      pairPrompt: "长者手机上显示的6位数字",
      pairDone: "已关联。",
    },
    activities: {
      title: "活动",
      create: "新建活动",
      name: "活动名称（体操、唱歌…）",
      intensity: "运动强度",
      intensityOpts: { none: "无", light: "轻", moderate: "中等" },
      start: "开始时间",
      end: "结束时间",
      roster: "参加的成员",
      save: "保存",
      summaryTitle: "活动前后一览",
      summaryNote: "仅供照护参考——显示活动前后的心情与身体状态，并非因果关系。",
      moodBetter: (n: number, total: number) => `${total}人中 ${n}人心情变好`,
      noCaptures: "还没有前后记录。",
    },
    weekly: {
      title: "每周录入",
      pedometer: "步数（周一）",
      pedometerHint: "请录入计步器上过去7天的数据。",
      clinical: "健康检查（周三）",
      grip: "握力(kg)",
      bp: "血压",
      weight: "体重(kg)",
      save: "保存",
      saved: "已保存。",
    },
    people: {
      title: "成员管理",
      add: "登记新成员",
      name: "姓名",
      photoUrl: "照片地址（可选）",
      platform: "手机类型",
      platformOpts: { ios: "iPhone", android: "安卓" },
      kiosk: "使用的设备",
      kioskFixed: "设定后不可更改。请始终使用同一台设备。",
      kioskNone: "尚未设定",
      checkinMode: "记录方式",
      checkinModeOpts: { self: "自己", self_nudge: "自己（带提醒）", staff: "员工协助" },
      save: "保存",
      saved: "已保存。",
      enrolled: "已登记成员",
      withdrawn: "已退出",
      withdraw: "退出",
      restore: "重新登记",
      confirmWithdraw: "把这位成员从名单移除吗？记录会保留。",
      consentTitle: "照护同意",
      consentSelf: "本人可以自行同意",
      consentRecords: "同意保留今天的记录",
      consentPhoto: "同意在设备上显示照片",
      consentVoice: "使用语音记录（可选）",
      consentVoiceNote: "不保存语音，只保留记录所需的信息。",
      legalRepTitle: "法定代理人（本人无法同意时）",
      legalRepName: "代理人姓名",
      legalRepRel: "关系",
      legalRepPhone: "联系方式",
      baselineTitle: "健康基本信息",
      adl: "日常生活协助程度（ADL）",
      afFlag: "有心房颤动",
      afNote: "有心房颤动时，不使用心率变异值。心率仍会显示。",
      betaBlocker: "服用β受体阻滞剂",
      betaNote: "会影响心跳的重要信息，请务必确认。",
      rateControl: "服用控制心率的药物",
      anticholinergic: "服用抗胆碱药",
      meds: "所服药物（每行一种）",
      medsPlaceholder: "例：阿司匹林 100mg",
      contactsTitle: "紧急联系人",
      contactsNote: "供员工在需要时直接联系。任何情况下都不会自动联系。",
      contactName: "姓名",
      contactRel: "关系",
      contactPhone: "联系方式",
      contactShare: "同意分享联系方式",
      addContact: "添加联系人",
      removeContact: "删除",
    },
    study: {
      title: "心率记录资料",
      note: "只汇总不含姓名的记录用于导出。长者不会看到。",
      export: "导出 (JSON)",
      subject: "编号",
      date: "日期",
      duration: "时长(秒)",
      site: "部位",
      selfReport: "本人 (0–10)",
      ref: "参考设备",
      refInApp: "一起测量",
      refOffline: "单独测量",
      video: "视频",
      viewVideo: "查看视频",
      hasVideo: "有",
      noVideo: "无",
      empty: "还没有记录。",
      count: (n: number) => `${n} 条记录`,
      disabled: "此功能暂时不可用。",
      tabRecords: "记录",
      tabVitals: "测量值",
      tabProfiles: "基本信息",
      name: "姓名",
      birthYear: "出生年份",
      sexLabel: "性别",
      heightCm: "身高(cm)",
      systolic: "收缩压",
      diastolic: "舒张压",
      bodyTemp: "体温(℃)",
      weightKg: "体重(kg)",
      sleepHours: "睡眠(小时)",
      activityRate: "活动量",
      save: "保存",
      saved: "已保存。",
      vitalsNeedRecording: "需要先有记录才能填写测量值。",
      profilesEmpty: "没有已登记的成员。",
    },
    nav: { today: "今天", activities: "活动", weekly: "每周" },
    navPeople: "成员管理",
    navStudy: "导出记录",
  },
  common: {
    loading: "请稍等…",
    error: "出错了，请再试一次。",
    back: "返回",
    confirm: "确定",
  },
};

// Missing keys in any locale fall back to English so nothing ever renders blank.
function deepMerge<T>(base: T, over: any): T {
  if (over == null) return base;
  const out: any = Array.isArray(base) ? [...(base as any)] : { ...(base as any) };
  for (const k of Object.keys(over)) {
    const b: any = (base as any)?.[k];
    const o: any = over[k];
    out[k] =
      o && b && typeof o === "object" && !Array.isArray(o) && typeof o !== "function"
        ? deepMerge(b, o)
        : o;
  }
  return out;
}

export const DICT: Record<Locale, Copy> = {
  en,
  ko: deepMerge(en, ko),
  es: deepMerge(en, es),
  zh: deepMerge(en, zh),
};

// DB band values are Korean (band_t enum). Map to the language-neutral key used
// by trends.bandLabel so the label can render in any language.
export const BAND_KEY: Record<string, "calm" | "load" | "rest"> = {
  "안정": "calm",
  "부담": "load",
  "소진": "rest",
};

// Three-band display: the band is ALWAYS shown with its reason (Invariant 1),
// and never any number. Colors are language-independent.
export const BAND_COLORS: Record<string, string> = {
  안정: "bg-band-calm",
  부담: "bg-band-load",
  소진: "bg-band-rest",
};
